### ISSUE TITLE
timestamp issue?

### ISSUE THREAD

**Issue by rantanlan** [AlbinLind/dawarich-home-assistant#2]
first lemme say thanks for this addon, I was to lazy to set it up myself with the scripts from the dawarich repro and I welcome the need of one less app :)

I created a new dawarich user to test this and to check the difference between owntracks, one thing I noticed all timestamps are coming in with current date and the same timestamp. is this an issue on your end? all software is updated to the latest versions.

![image](https://github.com/user-attachments/assets/fc3e0717-9e71-4fa3-9676-95a5ef5103d4)

**Comment by AlbinLind** [comment]
Thanks a lot for this report, and I am glad this might be useful for you!

It is indeed a bug in the API, having the default time be `datetime.date` instead of `datetime.datetime` I will push a new release with the fix.

**Comment by AlbinLind** [comment]
Should be fixed in #3, so you should be able to go to HACS go to Dawarich and press `Update information` you should then be able to update it, and it should be fixed. If it still persist, please re-open this issue, or if you have any other problems let me know :)

Thanks!
