### ISSUE TITLE
Timzone offset

### ISSUE THREAD

**Issue by noway42** [AlbinLind/dawarich-home-assistant#6]
Hi there,

thanks for this integration, I really appreciate it.

But I have a major issue when I use it: There is some offset in the timestamp/timezone.
I configured the server, Dawarich and Home Assistant to be in the same Timezone, but all datapoints from this integration are one hour in the future. E.g. now here it is 12:19, the most recent datapoint in Dawarich ist from today 13:04 (which should be from 12:04).

Do you have any advice on that?

**Comment by AlbinLind** [comment]
Could you confirm you are using version 0.3.1? The issue you're mentioning, should have been fixed in that patch.

If you're not on that version, try upgrading. If you are on 0.3.1 please let me know :)

**Comment by noway42** [comment]
You've got it. I was testing on 0.3 yesterday and didn't notice the update (had to refresh HACS manually after reading your reply to get it). With 0.3.1 it seems to work fine :-)
